### ISSUE TITLE
AssertionError: input feature has wrong size

### ISSUE THREAD

**Issue by Chenjingsuo** [tljxyys/Perspective-Unet#3]
我把img_sizeg改成了512，开始下面报错
C:\Users\user4\.conda\envs\GCtxUnet\python.exe E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py
Traceback (most recent call last):
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 610, in <module>
    output = model(input_tensor)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 601, in forward
    encoder_skips = self.encoder(x)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 524, in forward
    feature_trans = self.Encoder2(features) if self.Encoder2 is not None else features[-3:]
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 419, in forward
    feature_trans = stage(feature)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 340, in forward
    assert H == x.shape[-2] and W == x.shape[-1], "input feature has wrong size"
AssertionError: input feature has wrong size

我感觉是transform代码出错了，请问还需要改哪里，谢谢

**Comment by tljxyys** [comment]
请在TransformerEncoder类下对应修改**self.size**的参数

**Comment by Chenjingsuo** [comment]
C:\Users\user4\.conda\envs\GCtxUnet\python.exe E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py
Traceback (most recent call last):
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 610, in <module>
    output = model(input_tensor)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 601, in forward
    encoder_skips = self.encoder(x)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 527, in forward
    feature_trans = self.scale_integrator(feature_trans)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:/user4/Pycharm/Perspective-Unet-main/networks/perspective_unet.py", line 496, in forward
    hs_ws_splits = torch.split(transformed, split_sizes, dim=1)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\functional.py", line 189, in split
    return tensor.split(split_size_or_sections, dim)
  File "C:\Users\user4\.conda\envs\GCtxUnet\lib\site-packages\torch\_tensor.py", line 789, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 21504 (input tensor's size at dimension 1), but got split_sizes=[3136, 784, 196]

进程已结束,退出代码1
大佬，改完报错

**Comment by tljxyys** [comment]
SpatialCrossScaleIntegrator这个类下的self.h_w也对应修改一下呢，其他地方如果还有涉及到分辨率的参数也都需要修改一下

**Comment by Chenjingsuo** [comment]
Thanks for your help!
